name: CICD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  maven-installation:
    
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    - name: MVN Install
      run: |
        sudo apt update && sudo apt upgrade -y 
        sudo apt install openjdk-17-jdk -y 
        sudo apt install maven -y
        mvn --version
        
  compile:
    
    runs-on: self-hosted
    needs: maven-installation
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  security-check:

    runs-on: self-hosted
    needs: compile

    steps:
    - uses: actions/checkout@v4
    - name: Trivy installation
      run: |
        sudo apt-get install wget gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y
    
    - name: Trivy FS Scan
      run: trivy fs --format table -o fs-report.json .

    - name: Gitleaks Installation
      run: |
        wget https://github.com/gitleaks/gitleaks/releases/download/v8.29.0/gitleaks_8.29.0_linux_x64.tar.gz
        tar -xvzf gitleaks_8.29.0_linux_x64.tar.gz
        sudo mv gitleaks /usr/local/bin/

    - name: Gitleaks Code Scan
      run: gitleaks detect source . -r gitleaksreport.json -f json


  
